### ISSUE TITLE
How to trust certificates?

### ISSUE THREAD

**Issue by Antoniossss** [active-video/caching-proxy#23]
I have API endpoint over HTTPS that has certificate issued by internal CA. How can I trust such certificate?

Right now, proxy cannot connect due to:
` cache.handleUnhandledError() - An unhandled error occured fulfilling this request, Error: unable to verify the first certificate`

I am running proxy via `node caching-proxy/start.js`

**Comment by chwagssd** [comment]
This caching-proxy module does not support such a feature directly by way of any options you might be hoping. This is not a bug with the caching-proxy service here.

We use `follow-redirects` which in turn exposes the standard NodeJS HTTPs module options (@see https://nodejs.org/api/https.html#https_https_request_options_callback). 

However, without making changes to caching-proxy to accept insecure/untrusted certificates, you can also make use of the suggestion https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request#answer-21961005 provides.

**Comment by Antoniossss** [comment]
I already did and I disabled cert checking. Iv come into another "problem". In some cases, body string#replace can actually corrupt be body (I had to remove that).

Consider following case:

Having call to 

`localhost:8020/http://myrealdomain.com/use/some/api/myrealdomain.com/something/else`

with similar links in body like 

`http://myrealdomain.com/use/some/api/myrealdomain.com/something/another/thing`

will actually corrupt link in content resulting in 
`http://localhost:8020/use/some/api/localhost:8020/something/another/thing`

this is kind of special case, but it happened to me .

**Comment by chwagssd** [comment]
Good point, if the links are linkbacks to localhost:8020, then you could end up with multiple rewrites in there
