### ISSUE TITLE
All requests go to localhost

### ISSUE THREAD

**Issue by rolandstarke** [active-video/caching-proxy#26]
Hi,

I think this changes broke something: https://github.com/active-video/caching-proxy/commit/76e8263517c8dffe9ecfa60694d5359bfc6f1785

https://github.com/active-video/caching-proxy/blob/118acc0fccb5d1ddfe6db227496148cc48a2ade8/lib/caching-proxy.js#L244-L250

I started the proxy server with

```js
const proxy = new CachingProxy({
    port: 9090,
    dir: __dirname + '/cache',
});
```

And requested: http://localhost:9090/http/www.google.com

This results in the error: "An unexpected error occured in the CachingProxy: Error: connect ECONNREFUSED 127.0.0.1:80"

Thats because  `proxyHost`  is not configured so my ` options.host` is `undefined`.

**Comment by chwagssd** [comment]
you're right, ok let me get this fixed and update, thank you!

**Comment by chwagssd** [comment]
Ok, all fixed! Thanks a million for locating this bug, I've been rushing my updates lately and need to be more careful!
